### ISSUE TITLE
Should support elm-lang/core 4.0.x

### ISSUE THREAD

**Issue by avh4** [Kwarrtz/render#4]
The package currently limits the elm-lang/core version to <= 4.0.4.  I think the version bounds should be changed to

```
"elm-lang/core": "4.0.0 <= v < 5.0.0",
```

(was there a specific reason that v 4.0.5 doesn't work with this package?)

**Comment by Kwarrtz** [comment]
Thanks for pointing this one out to me. I had restricted core to v <= 4.0.4 during development because I was having some issues with 4.0.5 on my local machine. I fixed the problem, but looks like I never changed elm-package back. It should be fixed now.

**Comment by avh4** [comment]
Can you publish a new release with this fix?

**Comment by Kwarrtz** [comment]
v1.0.2 is out and includes this change. I had planned to bundle it with the v2.0.0 release but that ended up further behind schedule than I had anticipated. 

Thanks for reminding me about this one, by the way. I had completely forgotten about it.
