### ISSUE TITLE
Implement dashed line styles

### ISSUE THREAD

**Issue by avh4** [Kwarrtz/render#5]
The following example draws a solid line instead of a dashed line.

```elm
import Graphics.Render exposing (..)
import Color exposing (rgb)

main =
    segment ( 0, 0 ) ( 500, 500 )
        |> dashed 3 (rgb 80 80 80)
        |> svg canvasSize.width canvasSize.height
```

I noticed that currently the LineStyle in FLine is unused, so it looks like the code to generate the `stroke-dasharray` attribute (and maybe other attributes?) needs to be implemented.

I'll probably get around to making a PR for this later this month if no one else does so before then.

**Comment by Kwarrtz** [comment]
Fixed in v1.0.2
