### ISSUE TITLE
Publish new version that support Elm 0.18

### ISSUE THREAD

**Issue by avh4** [Kwarrtz/render#6]

**Comment by avh4** [comment]
FYI, this is blocked on https://github.com/jergason/elm-hash/pull/1

**Comment by Kwarrtz** [comment]
Hmm... it'll probably have to wait until the v2.0.0 release then, where I was planning to move away from elm-hash anyway. I should (finally) have time to work on that this weekend. No promises though.

**Comment by GreenHapi** [comment]
Yes, that would be nice! I hope you will have time to work on update

**Comment by Kwarrtz** [comment]
Moved to Elm 0.18 for v2.0.0. Sorry for the wait.
